// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3lCzG5y60h9Le_ohp-bbvLT4sktZIb4',
    appId: '1:9059968678:web:1193c12179b7b448f1b667',
    messagingSenderId: '9059968678',
    projectId: 'unijunction-68bd8',
    authDomain: 'unijunction-68bd8.firebaseapp.com',
    storageBucket: 'unijunction-68bd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuo4mkWwEHXnOg0CYTiTeI_9cP1IHycl4',
    appId: '1:9059968678:android:6275d7ef3845e1c5f1b667',
    messagingSenderId: '9059968678',
    projectId: 'unijunction-68bd8',
    storageBucket: 'unijunction-68bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwnslaxGg6tgt37PNsKBq0HwnZ2iBhFJ0',
    appId: '1:9059968678:ios:066f3a1c5da5b5b5f1b667',
    messagingSenderId: '9059968678',
    projectId: 'unijunction-68bd8',
    storageBucket: 'unijunction-68bd8.appspot.com',
    iosBundleId: 'com.example.authFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwnslaxGg6tgt37PNsKBq0HwnZ2iBhFJ0',
    appId: '1:9059968678:ios:3a4da649ce5a6692f1b667',
    messagingSenderId: '9059968678',
    projectId: 'unijunction-68bd8',
    storageBucket: 'unijunction-68bd8.appspot.com',
    iosBundleId: 'com.example.authFinal.RunnerTests',
  );
}
